trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Update to a more recent Node.js version if needed
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm install playwright  # Install Playwright
    npx playwright install  # Install Playwright browsers
  displayName: 'Install Playwright and browsers'

- script: |
    npm test  # Assuming you have a test script configured in package.json
  displayName: 'Run Playwright Tests'
